apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  labels:
    app: movie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: movie-backend
          image: koushikbijili/movie-app-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/movies"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-backend-service
spec:
  selector:
    app: movie-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

      targetPort: 5000
  type: ClusterIP


