apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  labels:
    app: movie-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
      - name: backend
        image: koushikbijili/movie-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-backend-service
spec:
  selector:
    app: movie-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

      port: 5000
      targetPort: 5000
  type: ClusterIP

