apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
  labels:
    app: movie-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/movie-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movie-frontend-service
spec:
  selector:
    app: movie-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
